apiVersion: apps/v1
kind: Deployment
metadata: 
  name: moodle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: docker.io/bitnami/moodle:4.1
          envFrom:
          - configMapRef:
              name: moodle-configmap
          imagePullPolicy: Always
      #     volumeMounts:
      #       - name: moodle-volume
      #         mountPath: /bitnami/moodle
      #       - name: moodledata-volume
      #         mountPath: /bitnami/moodledata
      # volumes:
      #   - name: moodle-volume
      #     persistentVolumeClaim:
      #       claimName: moodle-pvc
      #   - name: moodledata-volume
      #     persistentVolumeClaim:
      #       claimName: moodledata-pvc