apiVersion: v1
kind: Secret
metadata:
  name: moodle-secret
type: Opaque
stringData:
    ALLOW_EMPTY_PASSWORD: "yes"
    MARIADB_USER: "bn_moodle"
    MARIADB_DATABASE: "bitnami_moodle"
    MARIADB_CHARACTER_SET: "utf8mb4"
    MARIADB_COLLATE: "utf8mb4_unicode_ci"
